export const enum EmbedErrorCodes {
	COMMAND_INVALID = 400,
	COMMAND_NO_PERMISSION = 403,
	SONG_NOT_FOUND = 404,
	COMMAND_NOT_FOUND = 405,
	CHANNEL_NOT_SUPPORTED = 406,
	CHANNEL_NOT_CONNECTED = 420,
	NOT_PLAYING = 426,
	IS_ALREADY_PLAYING = 423,
	INDEX_OUT_OF_BOUNDS = 416,
}
